[
  {
    id: 2,
    user: {
      id: "testid",
      discordId: "testdiscordid",
      username: "discordusername",
      globalName: "discordglobalname",
      avatar:
        "https://cdn.discordapp.com/avatars/173602579530383361/53d40508e9e2f5a6d547066741106bb3.png?size=256",
      createdAt: "2026-09-15T20:24:26.367Z",
    },
    item: {
      name: "White Potion",
      iconUrl:
        "https://raw.githubusercontent.com/ohmi69/osms_datamine_dashboard/main/data/current/images/items/02000002.png",
      category: "Consumable",
      subCategory: "Consume",
      weaponType: null,
      attackSpeed: null,
      attackSpeedLabel: null,
      reqLevel: 0,
      reqSTR: 0,
      reqDEX: 0,
      reqLUK: 0,
      reqPOP: 0,
      totalUpgradeCount: null,
      baseStats: [],
      knockback: null,
      reqJobLabel: null,
      reqJobs: [],
      gender: null,
      storeSellPrice: 35,
      description:
        "A highly concentrated potion made out of red herbs.\nRestores 500 HP.",
    },
    world: {
      id: 1,
      name: "Windia",
    },
    type: "BUY",
    price: 123,
    quantity: 123,
    stats: [],
    remainingUpgradeSlots: null,
    createdAt: "2026-09-15T21:15:55.046Z",
    statDifferences: [],
    statDifferencesSum: 0,
  },
  {
    id: 1,
    user: {
      id: "testid",
      discordId: "testdiscordid",
      username: "discordusername",
      globalName: "discordglobalname",
      avatar:
        "https://cdn.discordapp.com/avatars/173602579530383361/53d40508e9e2f5a6d547066741106bb3.png?size=256",
      createdAt: "2026-09-15T20:24:26.367Z",
    },
    item: {
      name: "White Potion",
      iconUrl:
        "https://raw.githubusercontent.com/ohmi69/osms_datamine_dashboard/main/data/current/images/items/02000002.png",
      category: "Consumable",
      subCategory: "Consume",
      weaponType: null,
      attackSpeed: null,
      attackSpeedLabel: null,
      reqLevel: 0,
      reqSTR: 0,
      reqDEX: 0,
      reqLUK: 0,
      reqPOP: 0,
      totalUpgradeCount: null,
      baseStats: [],
      knockback: null,
      reqJobLabel: null,
      reqJobs: [],
      gender: null,
      storeSellPrice: 35,
      description:
        "A highly concentrated potion made out of red herbs.\nRestores 500 HP.",
    },
    world: {
      id: 1,
      name: "Windia",
    },
    type: "SELL",
    price: 123,
    quantity: 123,
    stats: [],
    remainingUpgradeSlots: null,
    createdAt: "2026-09-15T21:15:01.524Z",
    statDifferences: [],
    statDifferencesSum: 0,
  },
];
